USE [master]
GO

/****** Object:  Database [Echo]    Script Date: 3/2/2016 9:55:34 PM ******/
CREATE DATABASE [Echo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Echo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Echo.mdf' , SIZE = 11264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Echo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Echo_log.ldf' , SIZE = 16576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Echo] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Echo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Echo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Echo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Echo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Echo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Echo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Echo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Echo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Echo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Echo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Echo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Echo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Echo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Echo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Echo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Echo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Echo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Echo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Echo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Echo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Echo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Echo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Echo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Echo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Echo] SET  MULTI_USER 
GO

ALTER DATABASE [Echo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Echo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Echo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Echo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Echo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Echo] SET  READ_WRITE 
GO


