//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoClient.EchoDuplex {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Echo.Duplex", ConfigurationName="EchoDuplex.EchoDuplex", CallbackContract=typeof(EchoClient.EchoDuplex.EchoDuplexCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface EchoDuplex {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Echo.Duplex/EchoDuplex/Post")]
        void Post(System.IO.MemoryStream audioStream);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Echo.Duplex/EchoDuplex/Post")]
        System.Threading.Tasks.Task PostAsync(System.IO.MemoryStream audioStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EchoDuplexCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Echo.Duplex/EchoDuplex/Push")]
        void Push(System.IO.MemoryStream result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EchoDuplexChannel : EchoClient.EchoDuplex.EchoDuplex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoDuplexClient : System.ServiceModel.DuplexClientBase<EchoClient.EchoDuplex.EchoDuplex>, EchoClient.EchoDuplex.EchoDuplex {
        
        public EchoDuplexClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public EchoDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public EchoDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public EchoDuplexClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Post(System.IO.MemoryStream audioStream) {
            base.Channel.Post(audioStream);
        }
        
        public System.Threading.Tasks.Task PostAsync(System.IO.MemoryStream audioStream) {
            return base.Channel.PostAsync(audioStream);
        }
    }
}
