//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EchoClient.EchoWCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.Samples.GettingStarted", ConfigurationName="EchoWCFService.Echo")]
    public interface Echo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.GettingStarted/Echo/Post", ReplyAction="http://Microsoft.Samples.GettingStarted/Echo/PostResponse")]
        System.DateTime Post(System.Guid n1, byte[] n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.GettingStarted/Echo/Post", ReplyAction="http://Microsoft.Samples.GettingStarted/Echo/PostResponse")]
        System.Threading.Tasks.Task<System.DateTime> PostAsync(System.Guid n1, byte[] n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.GettingStarted/Echo/Get", ReplyAction="http://Microsoft.Samples.GettingStarted/Echo/GetResponse")]
        byte[] Get(System.Guid n1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.GettingStarted/Echo/Get", ReplyAction="http://Microsoft.Samples.GettingStarted/Echo/GetResponse")]
        System.Threading.Tasks.Task<byte[]> GetAsync(System.Guid n1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EchoChannel : EchoWCFService.Echo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EchoClient : System.ServiceModel.ClientBase<EchoWCFService.Echo>, EchoWCFService.Echo {
        
        public EchoClient() {
        }
        
        public EchoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EchoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EchoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime Post(System.Guid n1, byte[] n2) {
            return base.Channel.Post(n1, n2);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> PostAsync(System.Guid n1, byte[] n2) {
            return base.Channel.PostAsync(n1, n2);
        }
        
        public byte[] Get(System.Guid n1) {
            return base.Channel.Get(n1);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAsync(System.Guid n1) {
            return base.Channel.GetAsync(n1);
        }
    }
}
